// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz_TvUQ6N3AQ_dEMsBvw0sLMyftCYLv5A',
    appId: '1:485182792817:web:a1d4addd46e7c6664427d0',
    messagingSenderId: '485182792817',
    projectId: 'appmenfess',
    authDomain: 'appmenfess.firebaseapp.com',
    storageBucket: 'appmenfess.firebasestorage.app',
    measurementId: 'G-WYD4723VQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6dMa7fp1YRlvE3S0LBbYnSyDUoazySZc',
    appId: '1:485182792817:android:4411c0cba277f8064427d0',
    messagingSenderId: '485182792817',
    projectId: 'appmenfess',
    storageBucket: 'appmenfess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChC-C7_fng4YE5EEAlaewznhGHE3ubD0g',
    appId: '1:485182792817:ios:e20916a3a7f4275b4427d0',
    messagingSenderId: '485182792817',
    projectId: 'appmenfess',
    storageBucket: 'appmenfess.firebasestorage.app',
    iosBundleId: 'com.example.menfessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChC-C7_fng4YE5EEAlaewznhGHE3ubD0g',
    appId: '1:485182792817:ios:e20916a3a7f4275b4427d0',
    messagingSenderId: '485182792817',
    projectId: 'appmenfess',
    storageBucket: 'appmenfess.firebasestorage.app',
    iosBundleId: 'com.example.menfessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz_TvUQ6N3AQ_dEMsBvw0sLMyftCYLv5A',
    appId: '1:485182792817:web:2965e01638be7c8c4427d0',
    messagingSenderId: '485182792817',
    projectId: 'appmenfess',
    authDomain: 'appmenfess.firebaseapp.com',
    storageBucket: 'appmenfess.firebasestorage.app',
    measurementId: 'G-0ZXLMHK8FC',
  );
}
